safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Qqqing's Blog
host: buaaqingyuan.github.io/QqqingBlog
desc: Qqqing的个人博客

custom:
    category:
        deeplearning: Deep Learning
        nlp: NLP
        docker: Docker
        ml: Machine Learning
        is: Intelligent search
    categories:
      - name:  deeplearning
        title: Deep Learning

      - name:  nlp
        title: NLP

      - name:  docker
        title: Docker

      - name:  ml
        title: Machine Learning

      - name: is
        title: Intelligent Search

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: qqqing
        email: ae5656ln@163.com
        disqus: qqqing                              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: BUAAQingYuan                        # GitHub账号
        gitosc: buaalining                          # git@OSC账号
        gravatar: head.png                          # 用户头像

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
